insert into users (name,password) values ('Sam',123);

insert into person (name,created_by) values ('Riki',1);
insert into person (name,created_by) values ('Ev',1);
insert into person (name,created_by) values ('Evan',1);
insert into person (name,created_by) values ('Bella',1);
insert into person (name,created_by) values ('Isabellar',1);
insert into person (name,created_by) values ('Isabela',1);
insert into person (name,created_by) values ('Ollie',1);
insert into person (name,created_by) values ('Tanisha',1);
insert into person (name,created_by) values ('Reuben',1);
insert into person (name,created_by) values ('Rohit',1);
insert into person (name,created_by) values ('Ayana',1);
insert into person (name,created_by) values ('Helena',1);
insert into person (name,created_by) values ('Sam',1);
insert into person (name,created_by) values ('Seamus',1);
insert into person (name,created_by) values ('seamoose',1);
insert into person (name,created_by) values ('Father Dearest',1);
insert into person (name,created_by) values (' Dezmond',1);
insert into person (name,created_by) values ('dezzy',1);
insert into person (name,created_by) values (' Father',1);
insert into person (name,created_by) values ('Mr Gebbett',1);
insert into person (name,created_by) values (' Jim',1);
insert into person (name,created_by) values ('Dr Hudson',1);
insert into person (name,created_by) values (' hudson',1);
insert into person (name,created_by) values ('Mr Ob',1);
insert into person (name,created_by) values (' ob',1);
insert into person (name,created_by) values ('Mutsa',1);
insert into person (name,created_by) values ('Raja',1);
insert into person (name,created_by) values ('Lucy',1);
insert into person (name,created_by) values ('Hannah',1);
insert into person (name,created_by) values ('Tobias',1);
insert into person (name,created_by) values ('Tobais',1);
insert into person (name,created_by) values ('Tobis',1);
insert into person (name,created_by) values ('Taron',1);
insert into person (name,created_by) values ('Cj',1);
insert into person (name,created_by) values ('Giverney',1);
insert into person (name,created_by) values ('Gingadabombadey',1);
insert into person (name,created_by) values ('Government',1);
insert into person (name,created_by) values ('Giverny',1);
insert into person (name,created_by) values ('Cam',1);
insert into person (name,created_by) values ('Zac',1);
insert into person (name,created_by) values ('Emily',1);
insert into person (name,created_by) values ('Nate',1);
insert into person (name,created_by) values ('Ilil',1);
insert into person (name,created_by) values ('Takai',1);
insert into person (name,created_by) values ('Ms Wong',1);
insert into person (name,created_by) values ('Wong',1);
insert into person (name,created_by) values ('Gaia',1);
insert into person (name,created_by) values ('Naira',1);
insert into person (name,created_by) values ('Arla',1);
insert into person (name,created_by) values ('Linguini',1);
insert into person (name,created_by) values ('Eske',1);
insert into person (name,created_by) values ('Jessica',1);
insert into person (name,created_by) values ('ilils mate',1);
insert into person (name,created_by) values ('Gareth',1);
insert into person (name,created_by) values ('Will',1);
insert into person (name,created_by) values ('Mother',1);
insert into person (name,created_by) values ('Jasper',1);
insert into person (name,created_by) values ('Rome',1);
insert into person (name,created_by) values ('Jay',1);
insert into person (name,created_by) values ('Clara',1);
insert into person (name,created_by) values ('Ryan',1);
insert into person (name,created_by) values ('Caitlin',1);
insert into person (name,created_by) values ('Riley',1);
insert into person (name,created_by) values ('Nadia',1);
insert into person (name,created_by) values ('August',1);
insert into person (name,created_by) values ('September',1);
insert into person (name,created_by) values ('February',1);
insert into person (name,created_by) values ('March',1);
insert into person (name,created_by) values ('Ash',1);
insert into person (name,created_by) values ('Dean',1);
insert into person (name,created_by) values ('Luke',1);
insert into person (name,created_by) values ('Guys at work',1);
insert into person (name,created_by) values ('Padget',1);
insert into person (name,created_by) values ('Paget',1);
insert into person (name,created_by) values ('Pyper',1);
insert into person (name,created_by) values ('Maleesha',1);
insert into person (name,created_by) values ('Lara',1);
insert into person (name,created_by) values ('Mac',1);
insert into person (name,created_by) values ('Grace',1);
insert into person (name,created_by) values ('Tom',1);
insert into person (name,created_by) values ('Krish',1);
insert into person (name,created_by) values ('Ianna',1);
insert into person (name,created_by) values ('Jaymi',1);
insert into person (name,created_by) values ('Raihan',1);
insert into person (name,created_by) values ('David',1);
insert into person (name,created_by) values ('Sean Fitzimmons',1);
insert into person (name,created_by) values ('Jasmyn',1);
insert into person (name,created_by) values ('Jorge',1);
insert into person (name,created_by) values ('Sterling',1);
insert into person (name,created_by) values ('Dhruv',1);
insert into person (name,created_by) values ('Birui',1);
insert into person (name,created_by) values ('Kane',1);
insert into person (name,created_by) values ('Bernard',1);
insert into person (name,created_by) values ('Lauren',1);
insert into person (name,created_by) values ('Stephanie',1);
insert into person (name,created_by) values ('Sophie',1);
insert into person (name,created_by) values ('Katrin',1);
insert into person (name,created_by) values ('Kat',1);
insert into person (name,created_by) values ('Zoe',1);
insert into person (name,created_by) values ('Megan',1);
insert into person (name,created_by) values ('Bertil',1);
insert into person (name,created_by) values ('Holger',1);
insert into person (name,created_by) values ('└ucy',1);
insert into person (name,created_by) values ('murray',1);
insert into person (name,created_by) values ('Hetanshi',1);
insert into person (name,created_by) values ('Amike',1);
insert into person (name,created_by) values ('Nick',1);
insert into person (name,created_by) values (' Nicholas',1);
insert into person (name,created_by) values ('Flo',1);
insert into person (name,created_by) values ('Dilkee',1);
insert into person (name,created_by) values ('Olivia',1);
insert into person (name,created_by) values ('Grant',1);
insert into person (name,created_by) values ('Alex',1);
insert into person (name,created_by) values ('Omegl',1);
 call addQuote(ARRAY['$$To be fair my parents are cheese platter bitches$$'],ARRAY['Emily'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY['$$I was a massive paint eater$$'],ARRAY['Hannah'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY["$$I think there\\'s something wrong with Hannah", "It\\'s called celiac disease my guy$$"],ARRAY['Hannah', 'Linguini'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY['$$I love segregation$$'],ARRAY['Linguini'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY['$$I actually segregate based on the colour on the outside$$'],ARRAY['Linguini'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY["$$I don\\'t pay taxes. I am unemployed. Oh yeah$$"],ARRAY['Sam'],1,CAST('2023/08/27' AS DATE));
 call addQuote(ARRAY["$$I\\'m not a robbery girl, I\\'m a heist girl$$"],ARRAY['Giverney'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$no how do you deal with it its not like you can get vaccines or anything. Your family is literally just raw dogging it with the diseases.$$'],ARRAY['Riki', 'Hannah'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY["$$would you call your girlfriend a hoe? oh well, you wouldn\\'t know would you?$$"],ARRAY['Riki', 'Giverney'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$have you ever met a woman?$$'],ARRAY['Riki', 'Giverney'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$hoe singular is bad, hoes plural is ok$$'],ARRAY['Riki'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$name something worse than yellow', 'Kim Jong Un', 'No yellow is worse$$'],ARRAY['Zac'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$theres no one in this school whos more important than me$$'],ARRAY['Zac'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY["$$I need my seat back to draw Emily\\'s penis$$"],ARRAY['Taron'],1,CAST('2023/08/29' AS DATE));
 call addQuote(ARRAY["$$It\\'s enough to make a grown man cum$$"],ARRAY['Taron'],1,CAST('2023/08/30' AS DATE));
 call addQuote(ARRAY['$$gravity is not a thing$$'],ARRAY[' ob'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY['$$pin me daddy$$'],ARRAY['Taron'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY['$$I wanna flatten a year 7 so bad$$'],ARRAY['Taron'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY["$$Wow that\\'s a lot of testicles$$"],ARRAY['Seamus'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY['$$God the dating pool is small... and someone has pissed in it$$'],ARRAY['Nadia'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY["$$I\\'m about to be manipulated watch this.", "You\\'re used to it don\\'t worry$$"],ARRAY['Sam', 'Takai'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY['$$Stop being a slut and close your legs$$'],ARRAY['Sam', 'Takai'],1,CAST('2023/08/31' AS DATE));
 call addQuote(ARRAY['$$The fifth dimension is vibes$$'],ARRAY['Ayana'],1,CAST('2023/09/03' AS DATE));
 call addQuote(ARRAY["$$you\\'re basically 2D$$"],ARRAY['Sam', 'Seamus'],1,CAST('2023/09/03' AS DATE));
 call addQuote(ARRAY['$$Domestic violence is the solution to everything$$'],ARRAY['Nate'],1,CAST('2023/09/04' AS DATE));
 call addQuote(ARRAY["$$Not gonna lie I really wanted a drink in the morning so I\\'d be drunk at work$$"],ARRAY['Giverney'],1,CAST('2023/09/04' AS DATE));
 call addQuote(ARRAY['$$too much woman$$'],ARRAY['Tobis'],1,CAST('2023/09/04' AS DATE));
 call addQuote(ARRAY['$$Sam, you are the ugliest motherfucker I know$$'],ARRAY['Ev'],1,CAST('2023/09/04' AS DATE));
 call addQuote(ARRAY["$$I said why don\\'t we try capital punishment and they said that\\'s not the huanui way$$"],ARRAY['Nate'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$I am the most alt right person$$'],ARRAY['Rohit'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$I hate donuts but I like bagels... so its not the shape$$'],ARRAY['Rohit'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$im secretly the most racist person to ever exist. Take that liberals$$'],ARRAY['Rohit'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$if paracetamol was a person, it would be Mutsa$$'],ARRAY['Rohit'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$you a big basketball guy?$$'],ARRAY['Rohit'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$if sam were to be a bug, he would be An weevil$$'],ARRAY['Ev'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY['$$Or we could just Jesus the car$$'],ARRAY['Ayana'],1,CAST('2023/09/05' AS DATE));
 call addQuote(ARRAY["$$you know back in the day my reports used to say \\'Lynnette is arrogant\\'. I was 6$$"],ARRAY['Dr Hudson', ' hudson'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY["$$I was always a major criminal as I\\'m sure you can imagine$$"],ARRAY['Dr Hudson', ' hudson'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY["$$Taron if you\\'re going to pretend to read a book at least get one with pictures so its believable$$"],ARRAY[' ob'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY['$$its as usual, the rich stealing from others to make themselves richer.', 'I gotta support that tho.$$'],ARRAY['Dr Hudson', ' hudson', 'Ryan'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY['$$I love being smarter than the average person$$'],ARRAY['Riki'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY['$$I think Jo Mama would have a big penis if she was a man$$'],ARRAY['Giverney'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY["$$Rome\\'s like whole arse google, I\\'d explore it$$"],ARRAY['Takai'],1,CAST('2023/09/06' AS DATE));
 call addQuote(ARRAY["$$there\\'s not a large amount of pressure to fix the disaster that is the human knee$$"],ARRAY['Dr Hudson', ' hudson'],1,CAST('2023/09/07' AS DATE));
 call addQuote(ARRAY['$$a bone is a good thing to break$$'],ARRAY['Dr Hudson', ' hudson'],1,CAST('2023/09/07' AS DATE));
 call addQuote(ARRAY['$$I thought I ran like a disabled goat, like a really really disfigured goat$$'],ARRAY['Giverny'],1,CAST('2023/09/07' AS DATE));
 call addQuote(ARRAY["$$I\\'m sorry Rohit but you\\'re not going to slay as much as we are$$"],ARRAY['Jasper'],1,CAST('2023/09/08' AS DATE));
 call addQuote(ARRAY["$$- speaking of I am actually gonna kill myself before the singing competition so that we don\\'t have to do it", "I\\'m more than happy to do it$$"],ARRAY['Hannah'],1,CAST('2023/09/07' AS DATE));
 call addQuote(ARRAY['$$PB is temporary, 8 year no vom streak is forever$$'],ARRAY['Hannah'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY['$$I love it when someone exposes a dickhead$$'],ARRAY['Seamus'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY['$$I think mentally abusing year 12s is a good reason to come to work late$$'],ARRAY['Jasper'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY['$$I have touched everyone$$'],ARRAY['Takai'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY["$$Seven year no councilor streak, I\\'ve been rawdogging my mental health and I\\'m fine so far$$"],ARRAY['Hannah'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY["$$obviously you\\'re not into bondage", 'Obviously you are$$'],ARRAY['Takai'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY['$$you want my meat?', 'Yeah$$'],ARRAY['Riki', 'Rohit', 'Tobias'],1,CAST('2023/09/09' AS DATE));
 call addQuote(ARRAY['$$it feels like using a ladle to eat soup, just use a spoon$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$arguing with you is like arguing with a conniving genie$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$apostrophise$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$my horse testicles were exceedingly low, I think it was because I was in a hot climate$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY["$$I used to do gymnastics and ballet you know, those were some tough years. It\\'s a shocker I didn\\'t turn to alcohol$$"],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY["$$you\\'re a blemish on the oxford English dictionary$$"],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$then they show up and I say NO UNIONS FOR YOU! I say NO WORKERS RIGHTS!!$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$in all these quotes I just come off as a nazi$$'],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY["$$you haven\\'t heard the song mild laxitive qualities??!$$"],ARRAY['Rohit'],1,CAST('2023/09/10' AS DATE));
 call addQuote(ARRAY['$$all I know is that its 200 H Cash to buy a vape from the H tuck shop$$'],ARRAY['Giverney'],1,CAST('2023/09/11' AS DATE));
 call addQuote(ARRAY['$$i might go pro in go fish$$'],ARRAY['Zac'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY["$$I\\'m the biggest Daniel Campi hater out there$$"],ARRAY['Zac'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$hot take, alphabet spaghetti tastes better than normal spaghetti, just because of the shapes.$$'],ARRAY['Zac'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$Campi! Take some meds or do some work$$'],ARRAY[' ob'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$everything you do is a spit in the face of god$$'],ARRAY['Rohit'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY["$$I think if you have the balls to cheat in Dr Hudson\\'s class you deserve the marks$$"],ARRAY['Ryan'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$I wanted to kill him, just to do his teacher a favour you know$$'],ARRAY['Dr Hudson', ' hudson'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$this sounds like jizz music, you know the stuff they play in the cantina in star wars$$'],ARRAY['Taron'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY["$$It is my deepest darkest wish to be a fungus, I will live on people\\'s tosey wosies$$"],ARRAY['Ev'],1,CAST('2023/09/12' AS DATE));
 call addQuote(ARRAY['$$Jackie Chan would eat wenslydale cheese if he was still alive, did you know that?$$'],ARRAY['Ev'],1,CAST('2023/09/13' AS DATE));
 call addQuote(ARRAY['$$Taylor Swift music is a parasite$$'],ARRAY['Zac'],1,CAST('2023/09/14' AS DATE));
 call addQuote(ARRAY['$$singing is a pathetic act in itself, we are just alpha for being bad at it$$'],ARRAY['Giverney'],1,CAST('2023/09/14' AS DATE));
 call addQuote(ARRAY["$$You\\'re not here for your intellectual prowess, you\\'re here for a drink$$"],ARRAY['Ash'],1,CAST('2023/09/14' AS DATE));
 call addQuote(ARRAY["$$Outside of a dog, a book is a man\\'s best friend. Inside of a dog, it\\'s too dark to read$$"],ARRAY['Dean'],1,CAST('2023/09/14' AS DATE));
 call addQuote(ARRAY['$$No he has loving parents he is not straight bussin$$'],ARRAY['Ev'],1,CAST('2023/09/15' AS DATE));
 call addQuote(ARRAY["$$I\\'m doing Riki and then I\\'ve got maths papers$$"],ARRAY['Sam'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY["$$I\\'m regularly beaten by children$$"],ARRAY['Taron'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY["$$If you\\'re not a nutcase you\\'re not worth knowing$$"],ARRAY['Sam'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY["$$those are hard working shorts, there\\'s a lot of arse going on in there$$"],ARRAY['dezzy'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY['$$Noone can look an anteater in the eye and say they truly love them$$'],ARRAY['Rohit'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY['$$i hope they die, but not in an unethical corporate way$$'],ARRAY['Rohit'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY['$$if I could chose any animal to use as a football id chose an anteater$$'],ARRAY['Rohit'],1,CAST('2023/09/16' AS DATE));
 call addQuote(ARRAY['$$can I teabag you sam?$$'],ARRAY['Seamus'],1,CAST('2023/09/17' AS DATE));
 call addQuote(ARRAY["$$Another reason why he shouldn\\'t be alive$$"],ARRAY['Riki', 'Zac'],1,CAST('2023/09/17' AS DATE));
 call addQuote(ARRAY['$$I go hard for a cheese platter$$'],ARRAY['Riki'],1,CAST('2023/09/17' AS DATE));
 call addQuote(ARRAY["$$I\\'ve been told I\\'m pretty long$$"],ARRAY['Omegl'],1,CAST('2023/09/17' AS DATE));
 call addQuote(ARRAY['$$The osmotic power of jesus$$'],ARRAY['Riki'],1,CAST('2023/09/17' AS DATE));
 call addQuote(ARRAY["$$Riki looks like he\\'d be good at fingering$$"],ARRAY['Taron'],1,CAST('2023/09/18' AS DATE));
 call addQuote(ARRAY["$$You can\\'t do a Titanic, you\\'ve got no violin players$$"],ARRAY['Hannah'],1,CAST('2023/09/18' AS DATE));
 call addQuote(ARRAY['$$He is dumber than fucking Dory$$'],ARRAY['Taron', 'Naira'],1,CAST('2023/09/18' AS DATE));
 call addQuote(ARRAY['$$That lamb sounds so edible$$'],ARRAY['Taron'],1,CAST('2023/09/19' AS DATE));
 call addQuote(ARRAY['$$Squirt god dammit!!$$'],ARRAY['Taron'],1,CAST('2023/09/19' AS DATE));
 call addQuote(ARRAY["$$its just the thinking that\\'s hard to be honest$$"],ARRAY['Giverney'],1,CAST('2023/09/19' AS DATE));
 call addQuote(ARRAY['$$pull down your trousers$$'],ARRAY['Ayana'],1,CAST('2023/09/20' AS DATE));
 call addQuote(ARRAY['$$your body is a weird place$$'],ARRAY['Mutsa'],1,CAST('2023/09/20' AS DATE));
 call addQuote(ARRAY["$$Henry Cavil could literally do anything to me and I\\'d say sorry$$"],ARRAY['Takai'],1,CAST('2023/09/20' AS DATE));
 call addQuote(ARRAY["$$I\\'d agree with that$$"],ARRAY['Rohit'],1,CAST('2023/11/25' AS DATE));
 call addQuote(ARRAY['$$if I were a 60 year old British person, I would dominate the chase$$'],ARRAY['Hannah'],1,CAST('2023/09/20' AS DATE));
 call addQuote(ARRAY['$$I can feel my inner geezerness coming out$$'],ARRAY['Ev'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$Fuck I\\'m privaleged", 'Yeah I know, we all are$$'],ARRAY['Mutsa', 'Takai'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$I\\'ve just spooned your arse how do you feel about that?$$"],ARRAY['Riki', 'Tobias'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$i\\'m going to bust open my cock in this very van$$"],ARRAY['Riki', 'Emily'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY['$$I would have put up with your lazy arse for years if I knew wine was involved$$'],ARRAY[' ob'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$I\\'m getting drugs cause I\\'m a poor little thing$$"],ARRAY['Emily'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$Bees have a personal vendetta against me, I think it\\'s cause I don\\'t like the bee movie$$"],ARRAY['Emily'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY["$$I want to see a man\\'s chest$$"],ARRAY['Giverney'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY['$$He needs a slutty little man waist$$'],ARRAY['Giverney'],1,CAST('2023/09/21' AS DATE));
 call addQuote(ARRAY['$$All that intentionally being a smartarse? For nothing?$$'],ARRAY['Emily'],1,CAST('2023/09/22' AS DATE));
 call addQuote(ARRAY['$$imagine backwards intercourse$$'],ARRAY['Gaia'],1,CAST('2023/09/23' AS DATE));
 call addQuote(ARRAY['$$your head game is just too strong$$'],ARRAY['Riki'],1,CAST('2023/09/25' AS DATE));
 call addQuote(ARRAY['$$I wish I could actually eat Vaseline, I think it would make me feel so much better$$'],ARRAY['Ayana'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY['$$You should get your weenis pierced$$'],ARRAY['Ayana'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY['$$To enjoy housing, one must be a tory$$'],ARRAY['Rohit'],1,CAST('2023/07/26' AS DATE));
 call addQuote(ARRAY["$$I\\'m like Gadaffi$$"],ARRAY['Rohit'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY["$$It\\'s not about making sense, it\\'s about making dollars$$"],ARRAY['Rohit'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY["$$I feel like misogyny today, that\\'s my catchphrase$$"],ARRAY['Rohit'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY["$$I only bully the minorities, I\\'m like Nate$$"],ARRAY['Ev'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY["$$Engaging multiple titans? I\\'m not even married$$"],ARRAY['Rohit'],1,CAST('2023/09/26' AS DATE));
 call addQuote(ARRAY['$$Beat them! Beat the minorities$$'],ARRAY['Ev'],1,CAST('2023/09/28' AS DATE));
 call addQuote(ARRAY["$$marcel is not the penguin he\\'s just racist$$"],ARRAY['Ev'],1,CAST('2023/08/28' AS DATE));
 call addQuote(ARRAY['$$I hate Bulgarians$$'],ARRAY['Ev'],1,CAST('2023/10/02' AS DATE));
 call addQuote(ARRAY['$$I love the Bulgarian people, I just hate their legs is all$$'],ARRAY['Ev'],1,CAST('2023/10/02' AS DATE));
 call addQuote(ARRAY["$$oh my god you\\'re as thick as I am$$"],ARRAY['Ev'],1,CAST('2023/10/03' AS DATE));
 call addQuote(ARRAY['$$I am the crab man, give me a crab and I will consume his feety weeties$$'],ARRAY['Ev'],1,CAST('2023/10/05' AS DATE));
 call addQuote(ARRAY['$$I would beat up a year 2, easily$$'],ARRAY['Ev'],1,CAST('2023/10/06' AS DATE));
 call addQuote(ARRAY["$$call me ethanol cause I\\'m about to emulsify these bitches$$"],ARRAY['Rohit'],1,CAST('2023/10/06' AS DATE));
 call addQuote(ARRAY['$$You are crapping my balls$$'],ARRAY['Rohit'],1,CAST('2023/10/06' AS DATE));
 call addQuote(ARRAY['$$I wish I was an induction hob sometimes$$'],ARRAY['Ev'],1,CAST('2023/10/09' AS DATE));
 call addQuote(ARRAY["$$for a nutter he\\'s quite talented isn\\'t he$$"],ARRAY['dezzy'],1,CAST('2023/10/14' AS DATE));
 call addQuote(ARRAY['$$you ever just chow down on crispy lizards?$$'],ARRAY['Rohit'],1,CAST('2023/10/14' AS DATE));
 call addQuote(ARRAY['$$do you ever think worms get lonely?', 'also, side question, do you ever think worms get jealous of snakes$$'],ARRAY['Rohit'],1,CAST('2023/10/14' AS DATE));
 call addQuote(ARRAY["$$That\\'s shit! Bunch of crap! Bunch of ball juice!$$"],ARRAY['Rohit'],1,CAST('2023/10/14' AS DATE));
 call addQuote(ARRAY['$$noone likes the Germans$$'],ARRAY['Ev'],1,CAST('2023/10/16' AS DATE));
 call addQuote(ARRAY["$$The Italians, they\\'re all fun and games until you realize they invented fascisim$$"],ARRAY['Ev'],1,CAST('2023/10/16' AS DATE));
 call addQuote(ARRAY['$$I lowkey have the dream to be on the $100 note just to one up him$$'],ARRAY['Takai'],1,CAST('2023/10/16' AS DATE));
 call addQuote(ARRAY["$$You know what I\\'ve never understood? Depression. Just like be happy$$"],ARRAY['Taron'],1,CAST('2023/10/19' AS DATE));
 call addQuote(ARRAY['$$Male grooming? ', "I\\'ll groom males$$"],ARRAY['Riki', 'Ev'],1,CAST('2023/10/19' AS DATE));
 call addQuote(ARRAY["$$If I had a nickel for every time you had a surprise party, at your house, for a guy named Sam, I\\'d have two nickels, which isn\\'t a lot but it\\'s weird that it\\'s happened twice$$"],ARRAY['Hannah'],1,CAST('2023/10/19' AS DATE));
 call addQuote(ARRAY['$$I just want to be lightly racked$$'],ARRAY['Emily'],1,CAST('2023/10/19' AS DATE));
 call addQuote(ARRAY['$$who invented pseudocode', 'why?', 'i just want to sit down with them.... and skin them$$'],ARRAY['Rohit'],1,CAST('2023/10/19' AS DATE));
 call addQuote(ARRAY['$$I fucking love Bulgarian split squats, they make me wonder why I have legs$$'],ARRAY['Rohit'],1,CAST('2023/10/20' AS DATE));
 call addQuote(ARRAY['$$nobody wants lubed up insides$$'],ARRAY['Rohit'],1,CAST('2023/10/20' AS DATE));
 call addQuote(ARRAY["$$don\\'t question the big cock$$"],ARRAY['Rohit'],1,CAST('2023/10/21' AS DATE));
 call addQuote(ARRAY['$$I have never used 100% of my brain in my entire life$$'],ARRAY['Ev'],1,CAST('2023/10/23' AS DATE));
 call addQuote(ARRAY['$$Just bought a woman, feeling good$$'],ARRAY['Ev'],1,CAST('2023/10/24' AS DATE));
 call addQuote(ARRAY['$$I bounce for no man$$'],ARRAY['Takai'],1,CAST('2023/10/24' AS DATE));
 call addQuote(ARRAY["$$I\\'m an angsty teenager$$"],ARRAY['Rohit'],1,CAST('2023/10/28' AS DATE));
 call addQuote(ARRAY["$$I\\'ve not said the c word for nearly 5 minutes.$$"],ARRAY['Sam'],1,CAST('2023/10/30' AS DATE));
 call addQuote(ARRAY['$$Oh my god I said it, oh dear.$$'],ARRAY['Sam'],1,CAST('2023/10/30' AS DATE));
 call addQuote(ARRAY['$$I would buy a child for $40 and a bag of rice$$'],ARRAY['Ev'],1,CAST('2023/11/01' AS DATE));
 call addQuote(ARRAY['$$The real tequila was the friends we made along the way$$'],ARRAY['Sam'],1,CAST('2023/11/04' AS DATE));
 call addQuote(ARRAY['$$We were just talking about drinking milk straight from the tit$$'],ARRAY['Emily'],1,CAST('2023/11/04' AS DATE));
 call addQuote(ARRAY["$$I didn\\'t want a gay son with Riki$$"],ARRAY['Rohit'],1,CAST('2023/11/04' AS DATE));
 call addQuote(ARRAY['$$I wish my name was idiot-nincompoop$$'],ARRAY['Gingadabombadey'],1,CAST('2023/11/04' AS DATE));
 call addQuote(ARRAY['$$All that is liquid is not booze$$'],ARRAY['Rohit'],1,CAST('2023/11/04' AS DATE));
 call addQuote(ARRAY["$$I\\'m feeling nauseous but in a sexy way$$"],ARRAY['Rohit'],1,CAST('2023/11/07' AS DATE));
 call addQuote(ARRAY['$$Round 0.7933340008 to 9 Sig fig', '0.7933350000$$'],ARRAY['Ev'],1,CAST('2023/11/09' AS DATE));
 call addQuote(ARRAY['$$not to devalue what he does but most people his age are dead which gives him a small advantage$$'],ARRAY['dezzy'],1,CAST('2023/11/11' AS DATE));
 call addQuote(ARRAY['$$Sam you should become the next Martin Luther king$$'],ARRAY['Luke'],1,CAST('2023/11/12' AS DATE));
 call addQuote(ARRAY["$$Homophobes are a man\\'s best friend$$"],ARRAY['Rohit'],1,CAST('2023/11/12' AS DATE));
 call addQuote(ARRAY['$$what a wonderful day for a bit of casual racism$$'],ARRAY['Rohit'],1,CAST('2023/11/12' AS DATE));
 call addQuote(ARRAY['$$casual racism is where its at$$'],ARRAY['Rohit'],1,CAST('2023/11/12' AS DATE));
 call addQuote(ARRAY["$$i swear to god if i hear the phrase \\'cabinet reshuffle\\' come out of another BBC presenter\\'s mouth I will simply resort to mild terrorism$$"],ARRAY['Rohit'],1,CAST('2023/11/14' AS DATE));
 call addQuote(ARRAY["$$You\\'ve fiddled me... like a fiddle$$"],ARRAY['Nate'],1,CAST('2023/11/16' AS DATE));
 call addQuote(ARRAY['$$what are you doing down here you bony fuck', 'Did you bump into Sam?$$'],ARRAY['Seamus', 'Nate'],1,CAST('2023/11/16' AS DATE));
 call addQuote(ARRAY['$$all I have to keep me comapny is my ass$$'],ARRAY['Seamus'],1,CAST('2023/11/16' AS DATE));
 call addQuote(ARRAY['$$it was one of the emo phases of humaity$$'],ARRAY['Seamus'],1,CAST('2023/11/16' AS DATE));
 call addQuote(ARRAY["$$David, do you know how many men I\\'ve made cry today$$"],ARRAY['Nadia'],1,CAST('2023/11/16' AS DATE));
 call addQuote(ARRAY['$$I somehow sympathise with Nigel Farage now$$'],ARRAY['Rohit'],1,CAST('2023/11/18' AS DATE));
 call addQuote(ARRAY["$$that\\'s a drippy creamy horse$$"],ARRAY['Rohit'],1,CAST('2023/11/18' AS DATE));
 call addQuote(ARRAY['$$Any hoes at the moment?$$'],ARRAY['Riki'],1,CAST('2023/11/22' AS DATE));
 call addQuote(ARRAY["$$That is some really nice looking grass, it tickles me in a way I can\\'t explain$$"],ARRAY['Riki'],1,CAST('2023/11/22' AS DATE));
 call addQuote(ARRAY['$$Me and Riki went at it, it hurts. It hurts$$'],ARRAY['Seamus'],1,CAST('2023/11/23' AS DATE));
 call addQuote(ARRAY["$$I\\'ve found a good way to eat tofu, fry it lightly in butter, very lightly. And then throw it in the bin and get a steak$$"],ARRAY['Taron'],1,CAST('2023/11/23' AS DATE));
 call addQuote(ARRAY["$$I\\'m a fax bitch$$"],ARRAY['Emily'],1,CAST('2023/11/23' AS DATE));
 call addQuote(ARRAY["$$there\\'s no realism in apologies$$"],ARRAY['Rohit'],1,CAST('2023/11/24' AS DATE));
 call addQuote(ARRAY['$$every apology is just the liberal agenda trying to make you forget their crimes$$'],ARRAY['Rohit'],1,CAST('2023/11/24' AS DATE));
 call addQuote(ARRAY["$$Ask them if they\\'ve got any bleach", "No I\\'m not thirsty fuck off$$"],ARRAY['Ev', 'Rohit'],1,CAST('2023/11/25' AS DATE));
 call addQuote(ARRAY['$$Are you feeling racist yet?$$'],ARRAY['Ev', 'Rohit'],1,CAST('2023/11/25' AS DATE));
 call addQuote(ARRAY['$$They grind my gears a bit but I love them$$'],ARRAY['Ev'],1,CAST('2023/11/25' AS DATE));
 call addQuote(ARRAY['$$Shooting little kids is so much fun$$'],ARRAY['Riki'],1,CAST('2023/11/29' AS DATE));
 call addQuote(ARRAY["$$I won\\'t jerk you but I\\'ll have your balls$$"],ARRAY['Riki'],1,CAST('2023/11/29' AS DATE));
 call addQuote(ARRAY["$$I\\'m very pleasurable$$"],ARRAY['Riki'],1,CAST('2023/11/29' AS DATE));
 call addQuote(ARRAY["$$You\\'re gonna be my kitchen bitch$$"],ARRAY['Riki'],1,CAST('2023/11/29' AS DATE));
 call addQuote(ARRAY['$$This is one of the very few things that makes me genuinely want to kill myself$$'],ARRAY['Sam'],1,CAST('2023/11/29' AS DATE));
 call addQuote(ARRAY['$$Picking up a paintbrush is a gateway to painting and looking like me is a gateway to people falling in love with you all the time$$'],ARRAY['Lucy', 'murray'],1,CAST('2023/11/30' AS DATE));
 call addQuote(ARRAY["$$I thought that Noah\\'s ark was gonna happen and I wasn\\'t gonna be on the boat cause I was ginger$$"],ARRAY['Lucy'],1,CAST('2023/11/30' AS DATE));
 call addQuote(ARRAY["$$You can\\'t hit me I\\'m a woman", "I really don\\'t give a shit$$"],ARRAY['Ev', 'Lucy'],1,CAST('2023/11/30' AS DATE));
 call addQuote(ARRAY["$$I don\\'t have time for women$$"],ARRAY['Riki'],1,CAST('2023/11/30' AS DATE));
 call addQuote(ARRAY["$$He\\'s like dilute anthrax$$"],ARRAY['Rohit'],1,CAST('2023/12/02' AS DATE));
 call addQuote(ARRAY['$$Seamus is in all of us$$'],ARRAY['Seamus'],1,CAST('2023/12/03' AS DATE));
 call addQuote(ARRAY['$$I think your ass just attracts so many hands$$'],ARRAY['Sam', 'Seamus'],1,CAST('2023/12/06' AS DATE));
 call addQuote(ARRAY['$$oh, I have a knob$$'],ARRAY['Sam'],1,CAST('2023/12/06' AS DATE));
 call addQuote(ARRAY['$$Ram me from behind$$'],ARRAY['Taron'],1,CAST('2023/12/05' AS DATE));
 call addQuote(ARRAY["$$I can accept when I\\'m wrong... I just never am$$"],ARRAY['Lucy'],1,CAST('2023/12/08' AS DATE));
 call addQuote(ARRAY["$$It\\'s because I\\'m a vape Lord$$"],ARRAY['Hannah'],1,CAST('2023/12/08' AS DATE));
 call addQuote(ARRAY["$$Today I got \\'sick freckly tits\\'$$"],ARRAY['Gingadabombadey'],1,CAST('2023/12/08' AS DATE));
 call addQuote(ARRAY["$$The woke fucking leftists won\\'t let that happen$$"],ARRAY['Riki'],1,CAST('2023/12/09' AS DATE));
 call addQuote(ARRAY['$$Come and sniff the walls with me brother$$'],ARRAY['Ev'],1,CAST('2023/12/10' AS DATE));
 call addQuote(ARRAY['$$the only person allowed to piss my balls is me$$'],ARRAY['Rohit'],1,CAST('2023/12/11' AS DATE));
 call addQuote(ARRAY['$$it is I, Rohit, Pisser of balls$$'],ARRAY['Rohit'],1,CAST('2023/12/11' AS DATE));
 call addQuote(ARRAY["$$The worst part of this game is that you can\\'t kill kids$$"],ARRAY['Rohit'],1,CAST('2023/12/12' AS DATE));
 call addQuote(ARRAY['$$He has charisma, but that is all$$'],ARRAY['Cam'],1,CAST('2023/12/14' AS DATE));
 call addQuote(ARRAY["$$Gravity doesn\\'t even know who I am$$"],ARRAY['Hannah'],1,CAST('2023/12/16' AS DATE));
 call addQuote(ARRAY['$$Gay people is a sin$$'],ARRAY['Riley'],1,CAST('2023/12/16' AS DATE));
 call addQuote(ARRAY['$$Gluten free? What the fuck is that$$'],ARRAY['Guys at work'],1,CAST('2023/12/18' AS DATE));
 call addQuote(ARRAY['$$You see all this gluten free stuff but what does it mean?$$'],ARRAY['Guys at work'],1,CAST('2023/12/18' AS DATE));
 call addQuote(ARRAY['$$You know what they should be doing? They should be selling people to do manual labour$$'],ARRAY['Tobias'],1,CAST('2023/12/18' AS DATE));
 call addQuote(ARRAY["$$See it\\'s fine, what\\'s a little bit of debt every now and again?$$"],ARRAY['Sam'],1,CAST('2023/12/20' AS DATE));
 call addQuote(ARRAY['$$Straights are actually kinda good$$'],ARRAY['Riki'],1,CAST('2023/12/21' AS DATE));
 call addQuote(ARRAY["$$Now they\\'re calling poor people$$"],ARRAY['dezzy'],1,CAST('2023/12/22' AS DATE));
 call addQuote(ARRAY['$$I have a cerebellum', 'You do... in name only$$'],ARRAY['dezzy'],1,CAST('2023/12/22' AS DATE));
 call addQuote(ARRAY["$$It must be really hard to walk fast if you\\'re short. Must require some real thought$$"],ARRAY['Ev'],1,CAST('2023/12/23' AS DATE));
 call addQuote(ARRAY["$$I\\'m not a big splurger$$"],ARRAY['Rohit'],1,CAST('2023/12/28' AS DATE));
 call addQuote(ARRAY["$$I\\'m always mean to low level employees. I look at someone making minimum wage and I say \\'you should make less\\'$$"],ARRAY['Rohit'],1,CAST('2023/12/28' AS DATE));
 call addQuote(ARRAY['$$I have showers to have and things to splurge on$$'],ARRAY['Sam'],1,CAST('2023/12/28' AS DATE));
 call addQuote(ARRAY["$$He\\'s got his balls out", "Well he\\'s gotta keep his balls fresh$$"],ARRAY['Ev', 'Father Dearest', ' Father'],1,CAST('2023/12/29' AS DATE));
 call addQuote(ARRAY['$$He was a proper slag$$'],ARRAY['Megan'],1,CAST('2023/01/03' AS DATE));
 call addQuote(ARRAY["$$Stop wars? Don\\'t like that. Sounds like some weird version of star wars$$"],ARRAY['Ev'],1,CAST('2024/01/07' AS DATE));
 call addQuote(ARRAY['$$Holy guaca-monkey$$'],ARRAY['Ev'],1,CAST('2023/01/07' AS DATE));
 call addQuote(ARRAY["$$Look it\\'s Fred! The terminator!... Wait no that was Arnold$$"],ARRAY['Ev'],1,CAST('2024/01/07' AS DATE));
 call addQuote(ARRAY['$$No better way to start the day than stalking you $$'],ARRAY['Eske'],1,CAST('2024/01/10' AS DATE));
 call addQuote(ARRAY["$$It\\'s got to be Tchaikovsky, no other fucker would do that shit.$$"],ARRAY['Ev'],1,CAST('2024/01/13' AS DATE));
 call addQuote(ARRAY['$$I would fuck ducks all day long$$'],ARRAY['Riki'],1,CAST('2024/01/18' AS DATE));
 call addQuote(ARRAY['$$Something about Evan touching you all day$$'],ARRAY['Sam', 'Seamus', 'Taron'],1,CAST('2024/01/18' AS DATE));
 call addQuote(ARRAY["$$It\\'s not a dildo, it\\'s a wooden penis$$"],ARRAY['Seamus'],1,CAST('2024/01/20' AS DATE));
 call addQuote(ARRAY['$$A man with no fingers has more fine motor control than you.... schmuck$$'],ARRAY['Ev'],1,CAST('2024/01/13' AS DATE));
 call addQuote(ARRAY['$$Sam would be very easy to fit in like a suitcase$$'],ARRAY['Rohit'],1,CAST('2023/01/27' AS DATE));
 call addQuote(ARRAY['$$Sam you look very kidnappable$$'],ARRAY['Rohit'],1,CAST('2024/01/27' AS DATE));
 call addQuote(ARRAY["$$I don\\'t like to repent that\\'s true, I normally just like to giggle$$"],ARRAY['Rohit'],1,CAST('2024/01/27' AS DATE));
 call addQuote(ARRAY['$$I am like the Christopher Columbus of tutorials$$'],ARRAY['Rohit'],1,CAST('2024/01/27' AS DATE));
 call addQuote(ARRAY["$$Chickens don\\'t have wings$$"],ARRAY['Emily'],1,CAST('2024/01/29' AS DATE));
 call addQuote(ARRAY['$$They call me the hitman because I hit on men$$'],ARRAY['Nate'],1,CAST('2023/01/30' AS DATE));
 call addQuote(ARRAY['$$A good bit of smut is all you need in life$$'],ARRAY['Riki'],1,CAST('2024/02/03' AS DATE));
 call addQuote(ARRAY['$$Squeeze lemon on me and call me guacamole, thats bloody beautiful$$'],ARRAY['Ev'],1,CAST('2024/02/04' AS DATE));
 call addQuote(ARRAY["$$I\\'ll sour upon him when me mugs me$$"],ARRAY['Rohit'],1,CAST('2024/02/06' AS DATE));
 call addQuote(ARRAY['$$You are shitting my piss, no way$$'],ARRAY['Rohit'],1,CAST('2024/01/06' AS DATE));
 call addQuote(ARRAY["$$Because he\\'s thicc$$"],ARRAY['Ev'],1,CAST('2024/02/07' AS DATE));
 call addQuote(ARRAY["$$If you were to be a drug you\\'d be a laxative, because you\\'re shit... And you make me shit$$"],ARRAY['Ev'],1,CAST('2024/02/07' AS DATE));
 call addQuote(ARRAY['$$Someone stole my fucking pocket vodka, oh no$$'],ARRAY['Sam'],1,CAST('2024/02/09' AS DATE));
 call addQuote(ARRAY['$$I will jump, not in a sexual way, on your dick$$'],ARRAY['Caitlin'],1,CAST('2025/02/09' AS DATE));
 call addQuote(ARRAY["$$I\\'m literally John Football$$"],ARRAY['Ev'],1,CAST('2024/02/16' AS DATE));
 call addQuote(ARRAY["$$I like getting raped. It\\'s stimulating$$"],ARRAY['Riki', 'Taron'],1,CAST('2024/02/16' AS DATE));
 call addQuote(ARRAY['$$I tend to get on best with people who have motherly vibes, see you seem to have very motherly vibes Sam$$'],ARRAY['Emily'],1,CAST('2024/02/20' AS DATE));
 call addQuote(ARRAY["$$I\\'ll choke yah anytime$$"],ARRAY['Emily'],1,CAST('2024/02/20' AS DATE));
 call addQuote(ARRAY["$$Icecream is the devil\\'s weetbix$$"],ARRAY['September'],1,CAST('2024/02/22' AS DATE));
 call addQuote(ARRAY['$$His hunky ass is mine$$'],ARRAY['Sam', 'Taron', 'Emily'],1,CAST('2024/02/24' AS DATE));
 call addQuote(ARRAY['$$Oh my God that is an arse I would like to slap at least once$$'],ARRAY['Taron', 'Maleesha'],1,CAST('2024/02/25' AS DATE));
 call addQuote(ARRAY['$$I feel like if you were in the hunger games you would lose but like with dignity yah know?$$'],ARRAY['Sam', 'Paget'],1,CAST('2024/02/25' AS DATE));
 call addQuote(ARRAY['$$I find American people so uniquely entitled and self centered and annoying$$'],ARRAY['Emily'],1,CAST('2024/02/26' AS DATE));
 call addQuote(ARRAY["$$I\\'m gonna hit you so hard your teeth are gonna fly out of your fucking mouth$$"],ARRAY['Taron', 'Emily'],1,CAST('2024/02/26' AS DATE));
 call addQuote(ARRAY["$$Let\\'s have a three way$$"],ARRAY['Krish'],1,CAST('2024/02/26' AS DATE));
 call addQuote(ARRAY['$$Nerd$$'],ARRAY['Taron'],1,CAST('2024/02/28' AS DATE));
 call addQuote(ARRAY['$$I just use the thirst traps from tik tok to light my way around the room $$'],ARRAY['Paget'],1,CAST('2024/02/29' AS DATE));
 call addQuote(ARRAY['$$You smell better when you are awake Sam$$'],ARRAY['February'],1,CAST('2024/02/29' AS DATE));
 call addQuote(ARRAY['$$he turns me on what can I say$$'],ARRAY['Riki', 'Sam'],1,CAST('2024/02/29' AS DATE));
 call addQuote(ARRAY["$$my dad\\'s a Gemini, I\\'m an Aries, that could work. I already call him daddy$$"],ARRAY['Riki'],1,CAST('2024/02/29' AS DATE));
 call addQuote(ARRAY["$$He\\'s ripping a fat piss right now$$"],ARRAY['Emily'],1,CAST('2024/02/29' AS DATE));
 call addQuote(ARRAY["$$Maybe you shouldn\\'t be you, maybe you should be someone better$$"],ARRAY['March'],1,CAST('2024/03/01' AS DATE));
 call addQuote(ARRAY['$$Bitches be bonkers$$'],ARRAY['Jay', 'Jaymi'],1,CAST('2024/03/02' AS DATE));
 call addQuote(ARRAY['$$is winchester a country$$'],ARRAY['Pyper'],1,CAST('2024/02/05' AS DATE));
 call addQuote(ARRAY['$$balkan is a country?$$'],ARRAY['Maleesha'],1,CAST('2024/03/05' AS DATE));
 call addQuote(ARRAY['$$I am what my mother died of$$'],ARRAY['Paget'],1,CAST('2024/02/05' AS DATE));
 call addQuote(ARRAY['$$Elizabeth is not a moanable name$$'],ARRAY['Maleesha'],1,CAST('2024/03/07' AS DATE));
 call addQuote(ARRAY["$$guys I\\'m going through my non-committal hoe phase$$"],ARRAY['Pyper'],1,CAST('2024
/03/07' AS DATE));
